import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { createHash } from 'node:crypto'
import { afterEach, describe, expect, it } from 'vitest'
import { createStandardFrozenProject } from './presentation-standard-fixture.ts'
import { preparePresentationMaterials } from '../src/presentation/material-registry.ts'
import { buildPresentationStandardProject } from '../src/presentation/standard-project-adapter.ts'
import { publishPresentationStandardProjectIntoWorkspace } from '../src/presentation/workspace-project-writer.ts'
import type { VisualAssetRecord } from '../src/governance/types.ts'

const roots: string[] = []
afterEach(async () => { for (const root of roots.splice(0)) await rm(root, { recursive: true, force: true }) })

describe('explicit page visual fill', () => {
  it('reuses in-flight, persisted candidate and adopted requests while changed content gets a new identity', async () => {
    const { PageVisualFillService } = await import('../src/presentation/page-visual-fill.ts')
    const root = await mkdtemp(join(tmpdir(), 'pre-page-fill-')); roots.push(root)
    const source = createStandardFrozenProject()
    const records: VisualAssetRecord[] = []
    let requests = 0
    const dependencies = {
      governance: { readProject: () => ({ visualAssets: records }) },
      visual: {
        generate: async (_parent: unknown, task: { taskId: string }) => {
          requests += 1
          const asset: VisualAssetRecord = { assetId: `candidate-${requests}`, taskId: task.taskId, projectId: source.projectId,
            kind: 'concept', required: true, status: 'candidate', mimeType: 'image/png', fileName: 'candidate.png', sha256: createHash('sha256').update('candidate image bytes').digest('hex'),
            width: 1600, height: 900, createdAt: source.generatedAt, quality: { accepted: true, score: 1, issues: [] } }
          await writeFile(join(root, asset.fileName), 'candidate image bytes')
          records.push(asset)
          return asset
        },
        adopt: async (_projectId: string, assetId: string, revision: number) => {
          const i = records.findIndex(asset => asset.assetId === assetId)
          records[i] = { ...records[i]!, status: 'adopted', adoptedRevision: revision }
          return records[i]!
        },
      },
      resolveAsset: (fileName: string) => join(root, fileName),
    }
    const service = new PageVisualFillService(dependencies as never)
    const input = { frozenProject: source, workspaceRoot: root, findingId: 'pre-design:project-brief', prompt: '陆侧公共空间的概念示意', style: '克制、自然材料、无文字' }
    const [first, duplicate] = await Promise.all([service.generate({} as never, input), service.generate({} as never, input)])
    expect(first.assetId).toBe(duplicate.assetId)
    expect(requests).toBe(1)
    const restored = new PageVisualFillService(dependencies as never)
    expect(await restored.generate({} as never, input)).toMatchObject({ assetId: first.assetId, reused: true, status: 'candidate' })
    await expect(restored.adopt({ ...input, assetId: 'another-page-candidate' })).rejects.toThrow('PAGE_VISUAL_CANDIDATE_MISMATCH')
    const changedSource = { ...source, stateObjects: source.stateObjects.map(object => object.objectId === 'PS01'
      ? { ...object, facts: [{ label: '新增服务范围', value: '增加调蓄设施并核对征地范围', basis: '修订后的任务书' }] } : object) }
    await expect(restored.adopt({ ...input, frozenProject: changedSource, assetId: first.assetId })).rejects.toThrow('PAGE_VISUAL_BRIEF_CHANGED')
    expect(records[0]?.status).toBe('candidate')
    expect(await restored.adopt({ ...input, assetId: first.assetId })).toMatchObject({ status: 'adopted', assetId: first.assetId })
    expect(await restored.generate({} as never, input)).toMatchObject({ assetId: first.assetId, reused: true, status: 'adopted' })
    expect(requests).toBe(1)
    const adoptedInput = { sourceKey: first.assetId, sourcePath: join(root, 'candidate.png'), originalFileName: 'candidate.png',
      displayName: '概念候选', mimeType: 'image/png', semanticRole: 'concept_visual', widthPx: 1600, heightPx: 900,
      createdAt: source.generatedAt, adoptedAt: source.generatedAt, objectIds: ['PS01'], evidenceIds: [],
      origin: { type: 'generated_by_plugin' as const, sourceMaterialKeys: [], parentAssetKeys: [], method: 'generated by pre-design', sourceTool: { name: 'pre-design', version: '2.0.0' } } }
    const prepared = await preparePresentationMaterials({ frozenProject: source, workspaceRoot: root, assets: [adoptedInput] })
    expect(prepared.assets[0]?.pageBindingOnly).toBe(true)
    const build = await buildPresentationStandardProject({ frozenProject: source, ...prepared })
    await mkdir(join(root, 'layouts'))
    await writeFile(join(root, 'layouts/manual.json'), '{"manualFrame":"keep"}')
    const published = await publishPresentationStandardProjectIntoWorkspace({ directoryRoot: root, build, operationId: 'adopted-page-first' })
    const repeated = await preparePresentationMaterials({ frozenProject: source, workspaceRoot: root, assets: [adoptedInput],
      previous: { stableIds: build.stableIds, lastExportedFileHashes: published.fileHashes } })
    const rebuilt = await buildPresentationStandardProject({ frozenProject: source, ...repeated, stableIds: build.stableIds })
    const pages = (build.documents['pages/manifest.json'] as any).pages
    expect(pages.filter((page: any) => (rebuilt.documents[page.draftPath] as any).pageAssets.length > 0).map((page: any) => page.pageId))
      .toEqual([build.stableIds['page:finding:pre-design:project-brief']])
    for (const page of pages) expect((rebuilt.documents[page.draftPath] as any).pageAssets).toEqual((build.documents[page.draftPath] as any).pageAssets)
    const republished = await publishPresentationStandardProjectIntoWorkspace({ directoryRoot: root, build: rebuilt, operationId: 'adopted-page-second', expectedExistingFileHashes: published.fileHashes })
    expect(republished.validation.valid).toBe(true)
    expect(await readFile(join(root, 'layouts/manual.json'), 'utf8')).toBe('{"manualFrame":"keep"}')
    expect((rebuilt.documents['assets/manifest.json'] as any).assets[0].origin.type).toBe('generated_by_plugin')
    const changed = await restored.generate({} as never, { ...input, prompt: '公共空间的人视概念图' })
    expect(changed.taskId).not.toBe(first.taskId)
    expect(requests).toBe(2)
    const changedContent = await restored.generate({} as never, { ...input, frozenProject: changedSource })
    expect(changedContent.taskId).not.toBe(first.taskId)
    expect(requests).toBe(3)
    const state = JSON.parse(await readFile(join(root, '.pre-design/page-visual-fill.json'), 'utf8'))
    expect(state.requests.map((request: { findingId: string }) => request.findingId)).toEqual([input.findingId, input.findingId, input.findingId])
  })

  it('rejects unknown pages and cancellation before creating state or calling a model', async () => {
    const { PageVisualFillService } = await import('../src/presentation/page-visual-fill.ts')
    const root = await mkdtemp(join(tmpdir(), 'pre-page-fill-')); roots.push(root)
    const service = new PageVisualFillService({ visual: { generate: () => { throw new Error('MODEL_MUST_NOT_RUN') } } } as never)
    const input = { frozenProject: createStandardFrozenProject(), workspaceRoot: root, findingId: 'not-a-page', prompt: '概念', style: '自然' }
    await expect(service.generate({} as never, input)).rejects.toThrow('PAGE_VISUAL_FINDING_NOT_FOUND')
    await expect(service.generate({} as never, { ...input, findingId: 'pre-design:project-brief', signal: AbortSignal.abort(new Error('cancelled')) })).rejects.toThrow('cancelled')
    await expect(readFile(join(root, '.pre-design/page-visual-fill.json'))).rejects.toMatchObject({ code: 'ENOENT' })
  })
  it('records a failed generation without adoption or false coverage and blocks a second process lock', async () => {
    const { PageVisualFillService } = await import('../src/presentation/page-visual-fill.ts')
    const root = await mkdtemp(join(tmpdir(), 'pre-page-fill-')); roots.push(root)
    let calls = 0
    const service = new PageVisualFillService({ governance: { readProject: () => ({ visualAssets: [] }) },
      visual: { generate: async () => { calls += 1; throw new Error('fixed model unavailable') } } } as never)
    const input = { frozenProject: createStandardFrozenProject(), workspaceRoot: root, findingId: 'pre-design:project-brief', prompt: '安全陆侧公共空间', style: '低饱和' }
    await expect(service.generate({} as never, input)).rejects.toThrow('fixed model unavailable')
    const state = JSON.parse(await readFile(join(root, '.pre-design/page-visual-fill.json'), 'utf8'))
    expect(state.requests[0]).toMatchObject({ status: 'failed', message: 'fixed model unavailable' })
    const plan = await service.plan(input)
    expect(plan.pages.find(page => page.findingId === input.findingId)).toMatchObject({ covered: false, requestStatus: 'failed' })
    expect(plan.warnings.join()).toContain('fixed model unavailable')
    await writeFile(join(root, '.pre-design/page-visual-fill.lock'), '')
    await expect(service.generate({} as never, input)).rejects.toThrow('PAGE_VISUAL_BUSY')
    expect(calls).toBe(1)
  })
  it('does not count CAD or reference images as covered', async () => {
    const { PageVisualFillService } = await import('../src/presentation/page-visual-fill.ts')
    const root = await mkdtemp(join(tmpdir(), 'pre-page-fill-')); roots.push(root)
    await mkdir(join(root, '.pre-design'))
    await writeFile(join(root, 'plan.dwg'), 'AC1032')
    const source = createStandardFrozenProject()
    await writeFile(join(root, '.pre-design/materials.json'), JSON.stringify({ version: 1, projectId: source.projectId, materials: [{
      sourceKey: 'cad', sourcePath: 'plan.dwg', mimeType: 'image/vnd.dwg', importedAt: source.generatedAt,
      pageBindings: [{ findingId: 'pre-design:project-brief', role: 'primary' }],
    }] }))
    const service = new PageVisualFillService({ governance: { readProject: () => ({ visualAssets: [] }) },
      visual: { generate: () => { throw new Error('MODEL_MUST_NOT_RUN') } } } as never)
    const result = await service.plan({ frozenProject: source, workspaceRoot: root })
    expect(result.pages.find(page => page.findingId === 'pre-design:project-brief')).toMatchObject({ covered: false, imageCount: 0 })
    expect((await preparePresentationMaterials({ frozenProject: source, workspaceRoot: root })).assets).toHaveLength(1)
    await writeFile(join(root, 'reference.svg'), '<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600"/>')
    await writeFile(join(root, '.pre-design/materials.json'), JSON.stringify({ version: 1, projectId: source.projectId, materials: [{
      sourceKey: 'reference', sourcePath: 'reference.svg', mimeType: 'image/svg+xml', importedAt: source.generatedAt,
      metadata: { widthPx: 800, heightPx: 600 }, pageBindings: [{ findingId: 'pre-design:project-brief', role: 'reference' }],
    }] }))
    expect((await service.plan({ frozenProject: source, workspaceRoot: root })).pages.find(page => page.findingId === 'pre-design:project-brief')?.covered).toBe(false)
    await writeFile(join(root, '.pre-design/materials.json'), JSON.stringify({ version: 1, projectId: source.projectId, materials: [{
      sourceKey: 'reference', sourcePath: 'reference.svg', mimeType: 'image/svg+xml', importedAt: source.generatedAt,
      metadata: { widthPx: 800, heightPx: 600 }, pageBindings: [{ findingId: 'pre-design:project-brief', role: 'primary' }],
    }] }))
    expect((await service.plan({ frozenProject: source, workspaceRoot: root })).pages.find(page => page.findingId === 'pre-design:project-brief'))
      .toMatchObject({ covered: true, imageCount: 1 })
    await expect(service.generate({} as never, { frozenProject: source, workspaceRoot: root, findingId: 'pre-design:project-brief', prompt: '不替换已有图' }))
      .rejects.toThrow('PAGE_VISUAL_ALREADY_COVERED')
    await expect(readFile(join(root, '.pre-design/page-visual-fill.json'))).rejects.toMatchObject({ code: 'ENOENT' })
  })
})
