import { existsSync } from 'node:fs'
import { mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import { peerRequest } from './helpers/peer-research-fixture.ts'
import { registerPreplanningCommands } from '../src/commands/register.ts'
const url=new URL('../src/research-v2/peer-command.ts',import.meta.url)
async function api(){expect(existsSync(url),'peer command implementation exists').toBe(true);return import(url.href)}
const roots:string[]=[]
afterEach(async()=>{for(const r of roots.splice(0))await rm(r,{recursive:true,force:true})})
async function fixture(){const root=await mkdtemp(join(tmpdir(),'peer-command-'));roots.push(root);const q:any=peerRequest(),s=q.captures[0];await writeFile(join(root,'raw.json'),s.content);q.documents=[{sourceId:s.sourceId,label:s.label,locator:s.locator,observedAt:s.observedAt,retrievedAt:s.retrievedAt,claimClass:s.claimClass,rights:s.rights,mediaType:s.mediaType,path:'raw.json'}];delete q.captures;delete q.projectId;delete q.snapshotId;await writeFile(join(root,'peers.json'),JSON.stringify(q));await writeFile(join(root,'project.json'),JSON.stringify({projectId:'standard-project'}));return {root,q,deps:{readContext:()=>({project:{projectId:'project-peers',currentRevision:3}}),resolveBinding:()=>({root,standardProjectId:'standard-project'}),now:()=>new Date('2026-09-24T01:00:00Z')},invocation:{rawInput:'--input=peers.json',agent:{id:'session-test',session:{header:{cwd:root}}}}}}
describe('real peer command and workspace source intake',()=>{
 it('registers without removing legacy or regional commands',()=>{const names:string[]=[];registerPreplanningCommands({commands:{register:(d:any)=>names.push(d.name)}} as never,{} as never);expect(names).toContain('preplan-research-peers');expect(names).toContain('preplan-research-od');expect(names).toContain('preplan-run')})
 it('loads source documents and binds absent identity fields from the active workspace',async()=>{const a=await api(),f=await fixture(),c=a.createPeerResearchCommand(f.deps),response=await c.handler(f.invocation);expect(response.kind).toBe('success');const [id]=await readdir(join(f.root,'research/runs'));const r=JSON.parse(await readFile(join(f.root,'research/runs',id,'result.json'),'utf8'));expect(r.projectId).toBe('project-peers');expect(r.snapshotId).toBe('revision-3');expect(r.input.captures[0].sha256).toHaveLength(64);expect(response.text).toContain('未改变旧57项')})
 it('supports offline replay without reading changed original source files',async()=>{const a=await api(),f=await fixture(),c=a.createPeerResearchCommand(f.deps);await c.handler(f.invocation);const [id]=await readdir(join(f.root,'research/runs'));await writeFile(join(f.root,'raw.json'),'CHANGED');f.invocation.rawInput=`--verify=${id}`;expect(await c.handler(f.invocation)).toMatchObject({kind:'success',text:expect.stringContaining('复算通过')})})
 it('rejects another project before reading its requested documents or writing a run',async()=>{const a=await api(),f=await fixture();f.q.projectId='another-project';f.q.documents[0].path='../private';await writeFile(join(f.root,'peers.json'),JSON.stringify(f.q));const r=await a.createPeerResearchCommand(f.deps).handler(f.invocation);expect(r).toMatchObject({kind:'error',text:expect.stringContaining('RESEARCH_PROJECT_MISMATCH')});expect(existsSync(join(f.root,'research/runs'))).toBe(false)})
 it('rejects network flags, duplicate input and source path escape',async()=>{const a=await api(),f=await fixture(),c=a.createPeerResearchCommand(f.deps);for(const rawInput of ['--input=peers.json --online','--input=peers.json --input=peers.json','--input=../peers.json'])expect((await c.handler({...f.invocation,rawInput})).kind).toBe('error')})
 it('guards changed project revisions and leaves no committed run',async()=>{const a=await api(),f=await fixture();let reads=0;const deps={...f.deps,readContext:()=>({project:{projectId:'project-peers',currentRevision:++reads}})};expect(await a.createPeerResearchCommand(deps).handler(f.invocation)).toMatchObject({kind:'error',text:expect.stringContaining('RESEARCH_CONTEXT_CHANGED')});expect(await readdir(join(f.root,'research/runs'))).toHaveLength(0)})
 it('does not leak parser source values or absolute paths on malformed data',async()=>{const a=await api(),f=await fixture();f.q.peers[0].role='TOP_SECRET';await writeFile(join(f.root,'peers.json'),JSON.stringify(f.q));const r=await a.createPeerResearchCommand(f.deps).handler(f.invocation);expect(r.kind).toBe('error');expect(r.text).not.toContain('TOP_SECRET');expect(r.text).not.toContain(f.root)})
 it('can capture a saved HTML source without executing it',async()=>{const a=await api(),f=await fixture();await writeFile(join(f.root,'page.html'),'<h1>合成官方项目页</h1><script>throw new Error("injected")</script>');f.q.documents.push({...f.q.documents[0],sourceId:'page',mediaType:'text/html',path:'page.html',locator:'https://example.org/project'});f.q.peers[0].claims[0]={id:'name-from-page',field:'name',value:'合成官方项目页',sourceId:'page',selector:{type:'text-quote',quote:'合成官方项目页'}};await writeFile(join(f.root,'peers.json'),JSON.stringify(f.q));expect((await a.createPeerResearchCommand(f.deps).handler(f.invocation)).kind).toBe('success')})
})

it('rejects changed source bytes at the commit boundary instead of publishing stale inputs',async()=>{const a=await api(),f=await fixture();let reads=0;const deps={...f.deps,readContext:()=>{if(++reads===2){requireWrite()}return {project:{projectId:'project-peers',currentRevision:3}}}};function requireWrite(){requireFs.writeFileSync(join(f.root,'raw.json'),'{}')};const requireFs=await import('node:fs');expect(await a.createPeerResearchCommand(deps).handler(f.invocation)).toMatchObject({kind:'error',text:expect.stringContaining('RESEARCH_SOURCE_CHANGED')});expect(await readdir(join(f.root,'research/runs'))).toHaveLength(0)})
