import { existsSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { peerRequest } from './helpers/peer-research-fixture.ts'
const url=new URL('../src/research-v2/peer-analysis.ts',import.meta.url)
async function api(){expect(existsSync(url),'peer analysis implementation exists').toBe(true);return import(url.href)}
async function fixture(){const a=await import('../src/research-v2/source-intake.ts');const r=peerRequest();r.captures=r.captures.map(s=>a.createSourceCapture(s,s.content));return r}
describe('shared peer research',()=>{
 it('keeps nearby supply and external references distinct and never counts planned supply as operating',async()=>{const a=await api(),r=a.analyzePeers(await fixture());expect(r.rows).toHaveLength(3);expect(r.summary.operatingSupply).toBe(0);expect(r.summary.scenarioOperatingSupply).toBe(1);expect(r.summary.references).toBe(1);expect(r.publicationGranted).toBe(false)})
 it('retains zero as an explicit reported price, but missing data as unknown',async()=>{const a=await api(),q=await fixture();const price=q.peers[0].claims.find(c=>c.field==='price')!;(price.value as any).amount=0;const doc=JSON.parse(q.captures[0].content);doc.rows[0].price.amount=0;q.captures[0]=(await import('../src/research-v2/source-intake.ts')).createSourceCapture(q.captures[0],JSON.stringify(doc));const r=a.analyzePeers(q);expect(r.rows[0].cells.price.values[0].value.amount).toBe(0);expect(r.rows[2].cells.price.state).toBe('missing')})
 it('does not merge two branch identities merely because their names match',async()=>{const a=await api(),q=await fixture();q.peers.push({...structuredClone(q.peers[0]),peerId:'peer-other',claims:q.peers[0].claims.map(c=>({...c,id:c.id+'-other'}))});expect(a.analyzePeers(q).rows).toHaveLength(4)})
 it('preserves contradictory scalar sources instead of taking the latest',async()=>{const a=await api(),q=await fixture(),s=(await import('../src/research-v2/source-intake.ts')).createSourceCapture({...q.captures[0],sourceId:'other'},'{"status":"closed"}');q.captures.push(s);q.peers[0].claims.push({id:'conflict',field:'status',value:'closed',sourceId:'other',selector:{type:'json-pointer',pointer:'/status'}});const r=a.analyzePeers(q);expect(r.rows[0].cells.status.state).toBe('conflict');expect(r.summary.operatingSupply).toBe(0)})
 it('keeps target audience separate from sampled observed audience',async()=>{const a=await api(),r=a.analyzePeers(await fixture());expect(r.rows[0].cells.targetAudience.values[0].value).toBe('亲子家庭');expect(r.rows[0].cells.observedAudience.values[0].value.sampleSize).toBe(12);expect(r.rows[1].cells.observedAudience.state).toBe('missing')})
 it('rejects an observed audience without a sample and method',async()=>{const a=await api(),q=await fixture();q.peers[0].claims.find(c=>c.field==='observedAudience')!.value={description:'所有人都喜欢'};expect(()=>a.analyzePeers(q)).toThrow()})
 it('rejects duplicate peer or claim IDs, unbound values and future-dated records',async()=>{const a=await api();let q=await fixture();q.peers.push(q.peers[0]);expect(()=>a.analyzePeers(q)).toThrow('PEER_ID_DUPLICATE');q=await fixture();q.peers[0].claims[0].value='篡改名称';expect(()=>a.analyzePeers(q)).toThrow('SOURCE_VALUE_MISMATCH');q=await fixture();q.asOf='2026-08-01';expect(()=>a.analyzePeers(q)).toThrow('SOURCE_AFTER_ASOF')})
 it('does not turn self-declared facts into independently verified evidence',async()=>{const a=await api(),q=await fixture();q.captures[0]={...q.captures[0],claimClass:'fact'};const r=a.analyzePeers(q);expect(r.publicationGranted).toBe(false);expect(r.rows[0].cells.name.values[0].evidence.independentlyVerified).toBe(false)})
 it('refuses unknown CRS rather than guessing an offset',async()=>{const a=await api(),q=await fixture();q.peers[0].claims.find(c=>c.field==='coordinate')!.value={longitude:114,latitude:30,crs:'GCJ-02',entranceStatus:'source-recorded'};expect(()=>a.analyzePeers(q)).toThrow()})
 it('groups prices only by matching product basis, unit, currency and period',async()=>{const a=await api(),q=await fixture();const r=a.analyzePeers(q);expect(r.priceGroups[0].points).toHaveLength(1);expect(r.priceGroups[0].excludedPlanned).toBe(1);expect(r.summary.marketGapProven).toBe(false)})
 it('generates no OD request when origins or source-bound peer coordinates are absent',async()=>{const a=await api(),r=a.analyzePeers(await fixture());expect(a.preparePeerOd(r)).toMatchObject({request:null});expect(r.rows[1].cells.coordinate.state).toBe('missing')})
})

describe('evidence strength and incomparable prices',()=>{
 it('does not count assumed operating status as documented operating supply',async()=>{const a=await api(),r=a.analyzePeers(await fixture());expect(r.summary.operatingSupply).toBe(0);expect(r.summary.scenarioOperatingSupply).toBe(1);expect(r.priceGroups[0].evidenceBasis).toBe('scenario')})
 it('does not mix reported and assumed price points even with identical units',async()=>{const a=await api(),q=await fixture(),source=(await import('../src/research-v2/source-intake.ts'));const row=JSON.parse(q.captures[0].content).rows[0];q.captures.push(source.createSourceCapture({...q.captures[0],sourceId:'reported',claimClass:'source_conclusion'},JSON.stringify({row})));q.peers.push({...structuredClone(q.peers[0]),peerId:'reported-peer',claims:q.peers[0].claims.map(c=>({...c,id:'reported-'+c.id,sourceId:'reported',selector:{type:'json-pointer',pointer:'/row/'+c.field}}))});const r=a.analyzePeers(q);expect(r.priceGroups).toHaveLength(2);expect(r.summary.operatingSupply).toBe(1);expect(r.summary.scenarioOperatingSupply).toBe(1)})
 it('keeps different periods and units in different groups',async()=>{const a=await api(),q=await fixture();const doc=JSON.parse(q.captures[0].content);doc.rows[1].status='operating';doc.rows[1].price.unit='元/家庭';doc.rows[1].price.period='2026-08';q.captures[0]=(await import('../src/research-v2/source-intake.ts')).createSourceCapture(q.captures[0],JSON.stringify(doc));q.peers[1].claims.find(c=>c.field==='status')!.value='operating';q.peers[1].claims.find(c=>c.field==='price')!.value=doc.rows[1].price;expect(a.analyzePeers(q).priceGroups).toHaveLength(2)})
 it('excludes conflicting prices rather than silently averaging them',async()=>{const a=await api(),q=await fixture(),price=structuredClone(q.peers[0].claims.find(c=>c.field==='price')!);(price.value as any).amount=1;const s=(await import('../src/research-v2/source-intake.ts')).createSourceCapture({...q.captures[0],sourceId:'other-price'},JSON.stringify({price:price.value}));q.captures.push(s);q.peers[0].claims.push({...price,id:'other-price',sourceId:'other-price',selector:{type:'json-pointer',pointer:'/price'}});const r=a.analyzePeers(q);expect(r.rows[0].cells.price.state).toBe('conflict');expect(r.priceGroups.flatMap((g:any)=>g.points)).toHaveLength(0)})
 it('rejects a percentage indicator lacking its denominator',async()=>{const a=await api(),q=await fixture();q.peers[0].claims.find(c=>c.field==='metric')!.value={name:'occupancy',amount:60,unit:'%',period:'2026-09',denominator:null};expect(()=>a.analyzePeers(q)).toThrow()})
})

it('retains explicit exclusions and reasons but does not include them in supply or price summaries',async()=>{const a=await api(),q:any=await fixture();q.peers[0].selection='exclude';q.peers[0].selectionReason='样例功能不属于本次研究供给';const r=a.analyzePeers(q);expect(r.rows[0].selection).toBe('exclude');expect(r.summary.excluded).toBe(1);expect(r.summary.scenarioOperatingSupply).toBe(0);expect(r.priceGroups.flatMap((g:any)=>g.points)).toHaveLength(0)})
