import { wrapClientText } from '../report/client-typography.ts'
import type { PeerResult, PeerCell, PeerRow } from './peer-analysis.ts'
import type { PeerField } from './peer-schema.ts'
import { PEER_FIELDS } from './peer-schema.ts'

export const PEER_LABELS:Record<PeerField,string>={name:'项目名称',address:'地址',status:'营业状态',positioning:'定位',format:'业态',coordinate:'空间坐标',price:'产品价格',targetAudience:'目标客群',observedAudience:'观察客群',metric:'经营指标'}
const states={missing:'缺资料',recorded:'来源记载',limited:'条件性',conflict:'待消解冲突'}
const roles={direct:'直接竞品',substitute:'替代供给',reference:'模式参考（不计入周边供给）'}
export const peerEscape=(v:unknown)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;')
const csv=(v:unknown)=>{let s=typeof v==='string'?v:JSON.stringify(v);if(/^[\s]*[=+@\-\t\r]/u.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'}
export function peerCsv(rows:readonly (readonly unknown[])[]):string{return rows.map(r=>r.map(csv).join(',')).join('\r\n')+'\r\n'}
export function peerValueText(v:any):string {
  if(typeof v==='string')return ({operating:'来源记载营业',planned:'规划中',building:'建设中',closed:'已停业',unknown:'未明确'} as Record<string,string>)[v]??v
  if(v&&typeof v==='object'){
    if('offer'in v)return `${v.offer}：${v.amount} ${v.unit}（${v.currency}；${v.period}；${v.basis}）`
    if('sampleSize'in v)return `${v.description}；样本${v.sampleSize}；${v.method}；${v.period}`
    if('longitude'in v)return `${v.longitude}, ${v.latitude}；${v.crs}；${v.entranceStatus}`
    if('denominator'in v)return `${v.name}：${v.amount} ${v.unit}；${v.period}；分母${v.denominator??'未提供/非比例指标'}`
  }
  return JSON.stringify(v)
}
const nameOf=(r:PeerRow)=>r.cells.name.state==='conflict'?`${r.peerId}（名称冲突）`:String(r.cells.name.values[0]?.value??r.peerId)
const cellText=(c:PeerCell)=>c.state==='missing'?'未取得':c.values.map(v=>peerValueText(v.value)).join(' / ')
export function renderPeerMatrix(result:PeerResult):string {
  const fields:PeerField[]=['status','format','price','targetAudience','observedAudience','coordinate'],w=1200,h=130+result.rows.length*54
  const colors={missing:'#f1f2f2',recorded:'#d9ece6',limited:'#fff0d2',conflict:'#f4dad7'}
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" role="img" aria-label="项目资料覆盖矩阵（不是供给全覆盖证明）"><rect width="${w}" height="${h}" fill="white"/><g font-family="sans-serif" fill="#19383a"><text x="25" y="32" font-size="22">同类项目资料覆盖矩阵</text><text x="25" y="58" font-size="13">灰：缺失　绿：来源记载　黄：条件性　红：冲突；颜色不代表项目优劣。</text>${fields.map((f,i)=>`<text x="${360+i*135}" y="93" font-size="16">${PEER_LABELS[f]}</text>`).join('')}${result.rows.map((row,i)=>`<text x="25" y="${134+i*54}" font-size="16">${peerEscape(nameOf(row).slice(0,18))}</text>${fields.map((f,j)=>`<rect x="${346+j*135}" y="${108+i*54}" width="124" height="42" rx="4" fill="${colors[row.cells[f].state]}"/><text x="${356+j*135}" y="${134+i*54}" font-size="14">${states[row.cells[f].state]}</text>`).join('')}`).join('')}</g></svg>`
}
export function renderPeerPrices(result:PeerResult):string|null {
  const groups=result.priceGroups.filter(g=>g.points.length)
  if(!groups.length)return null
  let y=50;const chunks:string[]=[]
  for(const g of groups){const heading=`${g.evidenceBasis==='scenario'?'情景假设（非实际报价）':'来源报价'} / ${g.basis} / ${g.currency} / ${g.unit} / ${g.period}`;for(const line of wrapClientText(heading,65,Number.MAX_SAFE_INTEGER,'PEER_PRICE_COPY').split('\n')){chunks.push(`<text x="30" y="${y}" font-size="15">${peerEscape(line)}</text>`);y+=23}y+=10;const max=Math.max(1,...g.points.map(p=>p.amount));for(const p of g.points){chunks.push(`<text x="30" y="${y+18}" font-size="14">${peerEscape(p.peerId)}</text><rect x="190" y="${y}" height="24" width="${(p.amount/max*650).toFixed(2)}" fill="#26786e"/><text x="${205+p.amount/max*650}" y="${y+18}" font-size="14">${peerEscape(p.amount)}</text>`);y+=40}y+=25}
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1100 ${y+45}" role="img" aria-label="相同口径的来源价格对比"><rect width="1100" height="${y+45}" fill="white"/><g font-family="sans-serif" fill="#19383a"><text x="30" y="23" font-size="16">不同口径分别绘图，不合并均价；单点仅表示来源报价。</text>${chunks.join('')}<text x="30" y="${y+20}" font-size="13">排除规划/停业/状态不明的项目；不是成交价或经营成功证明。</text></g></svg>`
}
export function peerTables(r:PeerResult):Record<string,string>{
  const registry=[['peer_ID','项目名称','角色（输入决定）','纳入/排除','决定理由','地址','来源营业状态','坐标','异常/限制','证据ID'],...r.rows.map(p=>[p.peerId,nameOf(p),roles[p.role],p.selection==='exclude'?'排除':'纳入',p.selectionReason,cellText(p.cells.address),cellText(p.cells.status),cellText(p.cells.coordinate),PEER_FIELDS.filter(f=>['missing','conflict'].includes(p.cells[f].state)).map(f=>`${PEER_LABELS[f]}:${states[p.cells[f].state]}`).join('；'),Object.values(p.cells).flatMap(c=>c.values.map(v=>v.claimId)).join('|')])]
  const detail=(fields:PeerField[])=>[['peer_ID','字段','状态','原始值/口径','claim_ID','来源ID','来源日期','来源性质','selector'],...r.rows.flatMap(p=>fields.flatMap(f=>p.cells[f].values.length?p.cells[f].values.map(v=>[p.peerId,PEER_LABELS[f],states[p.cells[f].state],peerValueText(v.value),v.claimId,v.evidence.sourceId,v.evidence.observedAt,v.evidence.claimClass,JSON.stringify(v.evidence.selector)]):[[p.peerId,PEER_LABELS[f],'缺资料','未取得','','','','','']]))]
  return {'datasets/peer-registry.csv':peerCsv(registry),'datasets/peer-products.csv':peerCsv(detail(['positioning','format','price'])),
    'datasets/peer-operations.csv':peerCsv(detail(['targetAudience','observedAudience','metric']))}
}
export function renderPeerReport(r:PeerResult,matrix:string,prices:string|null,sourcePaths:Readonly<Record<string,string>>,odGaps:readonly string[]):string {
  const x=peerEscape
  const cell=(c:PeerCell)=>`<span class="badge ${c.state}">${states[c.state]}</span>${c.values.length?c.values.map(v=>`<p>${x(peerValueText(v.value))} <a href="#evidence-${x(v.claimId)}">[${x(v.claimId)}]</a></p>`).join(''):'<p>未取得；不按0处理。</p>'}`
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>同类项目证据对照 · ${x(r.input.scope)}</title><style>
:root{--ink:#19383a;--accent:#26786e;--muted:#607578;--line:#dbe6e3}*{box-sizing:border-box}body{margin:0;color:var(--ink);background:#f2f6f5;font:15px/1.75 system-ui,"Microsoft YaHei",sans-serif}main{max-width:1380px;margin:auto;padding:36px 30px 70px}h1{font-size:32px;line-height:1.4;margin:12px 0}h2{font-size:23px;margin:42px 0 18px}h3{font-size:18px;margin:0 0 10px}p{margin:8px 0}a{color:var(--accent);overflow-wrap:anywhere}header{background:#153d40;color:#fff;border-radius:18px;padding:28px 32px}header small{color:#b7d6d0}.notice{border-left:4px solid #c39342;background:#fff7e8;padding:14px 18px;margin:20px 0}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:20px 0}.stats div,.card{background:white;border:1px solid var(--line);border-radius:12px;padding:20px}.stats b{display:block;font-size:28px}.stats span{font-size:13px;color:var(--muted)}nav{display:flex;gap:20px;flex-wrap:wrap;margin:18px 0}svg{width:100%;height:auto;display:block}.scroll{overflow-x:auto;background:white;border:1px solid var(--line);border-radius:12px}table{width:100%;border-collapse:collapse;min-width:920px;font-size:13px}th,td{text-align:left;vertical-align:top;padding:14px;border-bottom:1px solid var(--line);max-width:280px;overflow-wrap:anywhere}th{background:#eaf1ee;font-weight:650}td p{margin:5px 0}.badge{display:inline-block;padding:2px 7px;font-size:11px;border-radius:5px;background:#eaf1ee}.missing{background:#efefef;color:#666}.limited{background:#fff0d2}.conflict{background:#f4dad7;color:#934a42}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.evidence{scroll-margin-top:12px}.evidence code{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}.small{font-size:12px;color:var(--muted)}button{padding:8px 14px;background:white;border:1px solid var(--line);border-radius:7px;cursor:pointer}@media(max-width:760px){main{padding:18px 12px}.stats,.grid{grid-template-columns:1fr 1fr}header{padding:20px}h1{font-size:25px}.grid{grid-template-columns:1fr}}@media print{body{background:white}main{max-width:none;padding:0}nav,button{display:none}header{background:white;color:#19383a;border:1px solid var(--line)}.scroll{overflow:visible}table{min-width:0;font-size:9pt}tr,.card{break-inside:avoid}svg{max-height:170mm}.grid{display:block}.card{margin-bottom:12px}@page{size:A3 landscape;margin:14mm}}</style></head><body><main>
<header><small>PRE-DESIGN / 2.1.0 / PEER RESEARCH</small><h1>周边竞品与同类项目：先区分证据，再判断供给</h1><p>${x(r.input.scope)} · 研究时点 ${x(r.input.asOf)}</p><small>快照 ${x(r.snapshotId)} · 条件性研究成果 / 未授予正式发布资格</small></header>
<div class="notice"><strong>未证明市场缺口。</strong>本页展示输入项目的来源对照，不代表已经穷尽周边项目；营业、价格与客群按来源日期和性质解读。样例假设不作为实测。</div>
<div class="stats"><div><b>${r.summary.total}</b><span>本次明确纳入的对象</span></div><div><b>${r.summary.operatingSupply}</b><span>来源记载营业的供给对象（不含假设）</span></div><div><b>${r.summary.references}</b><span>单列的模式参考</span></div><div><b>${r.summary.unknownStatus}</b><span>营业状态未知或冲突</span></div></div><p class="small">排除对象 ${r.summary.excluded} 个；另有 ${r.summary.scenarioOperatingSupply} 个对象仅在输入假设下营业，单列情景，不计入来源营业供给。</p>
<nav><a href="#supply">项目与空间</a><a href="#products">产品与价格</a><a href="#audiences">客群与经营</a><a href="#trace">逐字段证据</a><a href="#sources">原始来源</a><button onclick="window.print()">打印审查稿</button></nav>
<div class="card">${matrix}<p class="small">本图表达资料覆盖与冲突，不是项目评级，也不以颜色代表市场优劣。</p></div>
<h2 id="supply">01 / 共享项目清单与空间准备</h2><div class="scroll"><table><thead><tr><th>项目 / peer_ID</th><th>分类与纳入理由</th><th>营业状态与地址</th><th>坐标及出行准备</th></tr></thead><tbody>${r.rows.map(p=>`<tr><td><b>${x(nameOf(p))}</b><p>${x(p.peerId)}</p>${cell(p.cells.name)}</td><td>${p.selection==='exclude'?'<b>本轮排除</b> · ':''}${x(roles[p.role])}<p>${x(p.selectionReason)}</p><small>分类为输入决定，不由距离自动判定。</small></td><td>${cell(p.cells.status)}${cell(p.cells.address)}</td><td>${cell(p.cells.coordinate)}${p.cells.coordinate.state==='missing'?'<p>坐标缺失；不猜位置、不绘制虚构点位。</p>':''}</td></tr>`).join('')}</tbody></table></div><p class="small">${x(odGaps.join('；')||'已生成独立regional-od.request.json；路由仍需另行明确联网授权。')}</p>
<h2 id="products">02 / 定位、业态与同口径价格</h2>${prices?`<div class="card">${prices}</div>`:'<div class="notice">无可比且来源记载营业的价格记录；不填0，不生成虚假价格图。</div>'}<div class="scroll"><table><thead><tr><th>项目</th><th>定位</th><th>业态记录</th><th>产品报价与口径</th></tr></thead><tbody>${r.rows.map(p=>`<tr><td>${x(nameOf(p))}</td><td>${cell(p.cells.positioning)}</td><td>${cell(p.cells.format)}</td><td>${cell(p.cells.price)}</td></tr>`).join('')}</tbody></table></div>
<h2 id="audiences">03 / 目标客群、观察样本与经营指标</h2><div class="scroll"><table><thead><tr><th>项目</th><th>目标客群（非实际客流）</th><th>观察客群（样本与方法）</th><th>来源经营指标（非独立核验）</th></tr></thead><tbody>${r.rows.map(p=>`<tr><td>${x(nameOf(p))}</td><td>${cell(p.cells.targetAudience)}</td><td>${cell(p.cells.observedAudience)}</td><td>${cell(p.cells.metric)}</td></tr>`).join('')}</tbody></table></div>
<h2 id="trace">04 / 点到原始字段的追溯</h2><div class="grid">${r.rows.flatMap(p=>PEER_FIELDS.flatMap(f=>p.cells[f].values.map(v=>`<article class="card evidence" id="evidence-${x(v.claimId)}"><h3>${x(p.peerId)} / ${PEER_LABELS[f]}</h3><p>${x(peerValueText(v.value))}</p><p class="small">${x(v.claimId)} · ${x(v.evidence.claimClass)} · ${x(v.evidence.observedAt)}</p><code>${x(JSON.stringify(v.evidence.selector))}</code><p><a download href="${x(sourcePaths[v.evidence.sourceId])}">查看归档原始字节</a></p><code>SHA-256 ${x(v.evidence.sourceHash)}</code><p class="small">仅通过精确绑定检查；未独立核验真实性。</p></article>`))).join('')}</div>
<h2 id="sources">05 / 来源与限制</h2><div class="grid">${r.input.captures.map(s=>`<article class="card"><h3>${x(s.label)}</h3><p>${x(s.locator)}</p><p class="small">来源时点 ${x(s.observedAt)} / 采集 ${x(s.retrievedAt)}<br>来源类别 ${x(s.claimClass)} / 使用条件 ${x(s.rights)}</p><a download href="${x(sourcePaths[s.sourceId])}">完整包内原文文件</a><details><summary>展开原文（转义显示，不执行脚本）</summary><pre style="white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.6 monospace">${x(s.content)}</pre></details></article>`).join('')}</div><div class="notice">${r.limitations.map(l=>`<p>${x(l)}</p>`).join('')}</div><p class="small">研究所需的照片、许可底图、完整调查范围与现场复核尚未由本命令取得；本页不套用正式成果的图像数量门槛。</p></main></body></html>`
}
